### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by joel5638** [peace195/tensorflow-lite-yolo-v3#16]
trying to convert .weight to .pb

Traceback (most recent call last):
  File "convert_weights_pb.py", line 5, in <module>
    import yolo_v3
  File "/home/de-gpu-005/joel/tensorflow-lite-YOLOv3/yolo_v3.py", line 6, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

Please help

**Comment by InputBlackBoxOutput** [comment]
Use TensorFlow 1 
Have a look at issue #3
